# -*- coding: utf-8 -*-
"""
/***************************************************************************
 dummy
                                 A QGIS plugin
 dummy
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-01-17
        copyright            : (C) 2024 by foo
        email                : foo@foo.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'foo'
__date__ = '2024-01-17'
__copyright__ = '(C) 2024 by foo'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load dummy class from file dummy.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .dummy import dummyPlugin
    return dummyPlugin()
